// Generated by CoffeeScript 1.12.4
(function() {
  var MarkdownEditor, editor;

  MarkdownEditor = (function() {
    function MarkdownEditor(editorId, displayId) {
      this.editor = document.getElementById(editorId);
      this.display = document.getElementById(displayId);
      this.setOptions();
    }

    MarkdownEditor.prototype.setOptions = function() {
      var renderer;
      renderer = new marked.Renderer();
      renderer.code = function(code, language) {
        return '<pre' + '><code class="hljs">' + hljs.highlightAuto(code).value + '</code></pre>';
      };
      return marked.setOptions({
        breaks: true,
        renderer: renderer
      });
    };

    MarkdownEditor.prototype.subscriptEditorOnKeyUp = function() {
      var lazyFunc;
      lazyFunc = _.debounce(this.parseAndRenderMarkdown.bind(this), 300);
      return this.editor.addEventListener("keyup", lazyFunc);
    };

    MarkdownEditor.prototype.parseAndRenderMarkdown = function() {
      var formatted;
      formatted = marked(this.editor.value);
      return this.display.innerHTML = formatted;
    };

    return MarkdownEditor;

  })();

  editor = new MarkdownEditor("markdownEditor", "markdownDisplay");

  editor.subscriptEditorOnKeyUp();

}).call(this);
